CREATE TABLE CATEGORIA(
 id INT NOT NULL AUTO_INCREMENT,
 categoria VARCHAR(255),
 PRIMARY KEY (id) 
);

CREATE TABLE FUENTE(
 id INT NOT NULL AUTO_INCREMENT,
 fuente VARCHAR(255),
 PRIMARY KEY (id) 
);

CREATE TABLE AUTOR(
 id INT NOT NULL AUTO_INCREMENT,
 autor VARCHAR(255),
 PRIMARY KEY (id) 
);

CREATE TABLE NOTICIA(
 id INT NOT NULL AUTO_INCREMENT,
 title VARCHAR(255),
 url VARCHAR(255),
 fecha_publicacion DATE,
 fecha_ingreso DATE,
 FUENTE INT,
 AUTOR INT,
 CATEGORIA INT,
 PRIMARY KEY (id) 
);

